### ISSUE TITLE
Adding CSS enter/exit transition classes 

### ISSUE THREAD

**Issue by imolorhe** [patrick-steele-idem/morphdom#126]
I'm trying to figure out how to add CSS transition classes to elements in the template rendered using morphdom. I've tried using `onBeforeNodeAdded()` returning a new node with the CSS class added, and `onNodeAdded()` setting the CSS class, but they don't seem to work. Any other ideas on how to accomplish this?

**Comment by AutoSponge** [comment]
Maybe you could describe what's happening or provide a short demo. However, one common problem with animation is animations will "restart" when a node re-renders. This often happens when you're using another library to modify the node. To avoid this, you can use [`.isSameNode()`](https://github.com/patrick-steele-idem/morphdom/blob/4c04f7b66ba9e501f038d49e2d6605ecc1b34710/docs/virtual-dom.md#isSameNode) to make `morphdom` skip re-rendering your node while it's animating or while it's being manipulated by another library.

**Comment by tvogels** [comment]
@imolorthe, what is your solution?
