### ISSUE TITLE
Minor question about the source code

### ISSUE THREAD

**Issue by anwerso** [patrick-steele-idem/morphdom#25]
https://github.com/patrick-steele-idem/morphdom/blob/ea1444532c5b9717c508d41a4ff56a2fe508bce3/lib/index.js#L222

Is there any particular reason to not use strict equality comparison here?

**Comment by patrick-steele-idem** [comment]
The only reason I don't use strict equality is because I can save a byte and I am not concerned about type coercion since I know both the left hand side and the right hand side are strings.

Since you asked, I'm not of the opinion that strict equality checks should always be used. There's lots of situations where `==` or `!=` produces better code. It's just more important that the JavaScript language is understood and used appropriately... 

I hope that clarifies :)

**Comment by anwerso** [comment]
It definitely clarifies :)
