### ISSUE TITLE
Potential onBeforeNodeDiscarded

### ISSUE THREAD

**Issue by kesne** [patrick-steele-idem/morphdom#4]
I think there could be a use case for adding an `onBeforeNodeDiscarded` callback that could return `false` if the node should not be discarded. You can't use the `onNodeDiscarded` callback because that could be called on a deep node that isn't possible to retain in the tree. But if it can be retained (i.e. it's going to be removed from a node that we're keeping), then we can use the callback to allow it to be kept in the tree.

The reason I think this would be great is because it adds the ability for third party libraries to insert nodes without morphdom clearing them out.

**Example use case:** 
> A third party library I'm working with injects a DOM node when I use it. However, when I create a render a new HTML string, that node is not present in the render (because it was added by the third party lib, and is not a part of my template). Morphdom sees this new node, and notices it isn't present in the new markup, so it removes it.

In this case, you could just add a `onBeforeNodeDiscarded` callback that returns `false` on the injected node, thus keeping it in the tree.

**Comment by patrick-steele-idem** [comment]
Interesting that you mention that. We solved the problem by rendering a placeholder element with empty content purely for the purpose of marking where a DOM node should exist in the final DOM tree. We use the placeholder element in combination with `onBeforeMorphEl` to prevent DOM nodes from nodes that should not be rerendered from being discarded. Relevant code in Marko Widgets: 

- https://github.com/marko-js/marko-widgets/blob/38e1379878750fbbf324d353ec20a7b450052fa6/lib/Widget.js#L534-L553
- https://github.com/marko-js/marko-widgets/blob/38e1379878750fbbf324d353ec20a7b450052fa6/taglib/widget-tag.js#L25-L32

Does that seem like a reasonable solution? `onBeforeNodeDiscarded` might work but it doesn't allow the old node to move to a new location.

**Comment by kesne** [comment]
The only problem that I think that solution has is that it requires knowledge or control over the third party library. The one major benefit of `onBeforeNodeDiscarded` is that I could make a rule to ignore all nodes with the attribute `data-ignore` and keep those in the DOM. With a generic solution the integration with other libraries just gets simpler.

**Comment by patrick-steele-idem** [comment]
I'm not necessarily opposed to `onBeforeNodeDiscarded`. If you had a strong need I would suggest submitting a PR (with test cases). We can leave this issue open. Thanks.

**Comment by jholster** [comment]
I can also se how onBeforeNodeDiscarded could be potentially used for implementing (programmatic) animations. After performing the animation you call node.parentNode.removeChild(node), or maybe onBeforeNodeDiscarded could provide removeNode callback¹.

¹) maquettejs does that, see http://maquettejs.org/docs/animations.html

**Comment by DarkMarmot** [comment]
I'd like this feature as well. I'd probably fork to get it :)

**Comment by patrick-steele-idem** [comment]
:+1: 

Great point, @jholster. In one of my sample apps I wanted to animate the removal of an item that is deleted, but there is no easy way to do that right now since it is simply discarded from the DOM. If we had the hook to prevent the node from immediately being discarded then we could animate the removal and then remove the node in our own code.

@DarkMarmot, I'll be happy to review a PR if you have time to work on this. I think it would be a helpful feature to add and I don't think it is too difficult to implement since all removals are handled by the following function: https://github.com/patrick-steele-idem/morphdom/blob/459ccbfe30a87e9dbdab81b996b106560b31160b/lib/index.js#L154-L165

Please include additional tests if you are able to implement this new feature. Thanks!
