### ISSUE TITLE
Elements under `onBeforeElChildrenUpdated` element removed if they have `id` set

### ISSUE THREAD

**Issue by orthecreedence** [patrick-steele-idem/morphdom#78]
Hello! I've been using morphdom for a while without problems, but today I'm running into an issue (latest master) where the children of an element ignored by `onBeforeElChildrenUpdated` are being removed, seemingly only if they have `id` set.

I've narrowed this down to here: https://github.com/patrick-steele-idem/morphdom/blob/master/src/index.js#L537

Looks like `indexTree` puts all the elements in the tree into an object (`fromNodesLookup`) indexed by `id`  and once the DOM is morphed, the indexed elements are all removed. It also looks like `id`s are deleted from `fromNodesLookup` if they are part of a `toEl` (https://github.com/patrick-steele-idem/morphdom/blob/master/src/index.js#L343) however this is not tracked when children are ignored.

I'm trying to think of potential fixes, and my first reaction is to check `onBeforeElChildrenUpdated` in `indexTree` and ignore all children if `false` is returned, but maybe there's a better way? I'm happy to fix and submit a PR if this is the way you want to go.

Thanks!

**Comment by AutoSponge** [comment]
A working example would be great, but I'll try to follow along. When you return `false` from `onBeforeElChildrenUpdated` you're skipping the subtree. Because things in the subtree have ids (which didn't match during `morphEl`) they get cleaned up.

The fix may involve `delete fromNodesLookup[...];` scoped to children of the `fromEl` that was morphed (but who wants to check every node in the lookup?). Or, it may be that `indexTree` needs to operate inside `morphEl`, after the `onBeforeElChildrenUpdated` check.

**Comment by orthecreedence** [comment]
Oh, interesting. I didn't even think about moving `indexTree` inside `morphEl`. Right now, the index is fully built before walking the DOM tree, and my worry is building it on the fly might have unintended side effects (for instance if checking for a moved node). That's why I'm wondering if just checking `onBeforeElChildrenUpdated` should be run inside of `indexTree` as well as inside `morphEl`.

BTW, here's an example: http://codepen.io/anon/pen/mEQNry

**Comment by AutoSponge** [comment]
Yeah, you're probably right about `indexTree` needing to pre-index. This may not fix your "real-world" issue but I added this to your codepen and it worked as expected:

```javascript
    onBeforeNodeDiscarded: function(node) {
      return !skip.contains(node)
    }
```

**Comment by orthecreedence** [comment]
Oh good plan. I also realized I can gather all sub-elements with ids and send them to `onBeforeNodeDiscarded`. This works pretty well too.

**Comment by patrick-steele-idem** [comment]
Sorry for be slow to respond, but I was on vacation for the past two days. I need to investigate a little further, but it sounds like we need to put in a fix to not remove keyed/IDed elements that are skipped when a DOM subtree is skipped due to a callback hook returning `false`. The workaround you provided does work, but probably not ideal. I'll take a closer look this morning. Thanks for reporting the problem.

**Comment by orthecreedence** [comment]
Cool, thanks!
