### ISSUE TITLE
Document `getNodeKey`?

### ISSUE THREAD

**Issue by mAAdhaTTah** [patrick-steele-idem/morphdom#79]
Looking through the source, I found [this](https://github.com/patrick-steele-idem/morphdom/blob/master/src/index.js#L228) but there' no documentation on what it does and what we'd want to do with it. Is there a reason this is undocumented? What's the backstory/use-case?

**Comment by patrick-steele-idem** [comment]
Thanks for brining this up. We do need to document the `getNodeKey` option, but I'll go ahead and add some notes here. One of the requirements of `morphdom` is that it always matches up "keyed" elements for diffing/patching. Keyed elements are elements that have a unique identifier and how that unique identifier gets assigned can vary by application. Originally, `morphdom` only supported the `id` attribute as the unique identifier, but others felt it was important to make this configurable and the `getNodeKey()` option was therefore introduced as PR.

Keyed elements are important because morphdom wants to match up the same elements between rerenders and an element may move to a new location in the DOM tree after a rerender. Internally, `morphdom` will index the source tree to find all keyed elements using tree walking code.

Does not help?

**Comment by mAAdhaTTah** [comment]
Oh, that is useful. Kind of like diffhtml's `key` attribute? I'll look into a PR for adding this to the documentation, if that helps.
